---
- name: create ansible directory
  file:
    path: /usr/share/tomcat/webapps/ansible
    state: directory

- name: copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: index.html.app2
    dest: /usr/share/tomcat/webapps/ansible/index.html

